//
// Created by nylund on 07.04.2022.
//

#ifndef REALTIME_POSE_ESTIMATION_INCLUDE_LOGGER_LOGGER_H_
#define REALTIME_POSE_ESTIMATION_INCLUDE_LOGGER_LOGGER_H_

class Logger {
 public:


 private:

};

#endif //REALTIME_POSE_ESTIMATION_INCLUDE_LOGGER_LOGGER_H_
